### ISSUE TITLE
Availability for Friday is the weekend availability instead of weekday

### ISSUE THREAD

**Issue by Spookyerol** [GKStretton/SE#115]

**Comment by Spookyerol** [comment]
The hour picker for friday (8th) is limited from 10 am to 4 pm instead of being 6 pm to 9:30 pm.

**Comment by nikeshpatel99** [comment]
I wouldnt worry about this too much, the time picker for the front end will be changed soon to be a dropdown choice to make it easier for hte user.

**Comment by Spookyerol** [comment]
Update: for the next friday (15th) it is giving the correct range. This might be an edge scenario where it glitches out on thursdays. I noticed it after the picker stopped allowing me to book on thursdays.

**Comment by nikeshpatel99** [comment]
Fixed #120
