### ISSUE TITLE
Favicon Issues

### ISSUE THREAD

**Issue by GKStretton** [GKStretton/SE#56]
Favicon does not display, and the following is printed in server console.

> Error thrown for request: /favicon.ico
> Error: Cannot find module 'ico'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
>     at Module.require (internal/modules/cjs/loader.js:657:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at new View (/home/greg/SE/node_modules/express/lib/view.js:81:14)
>     at Function.render (/home/greg/SE/node_modules/express/lib/application.js:570:12)
>     at ServerResponse.render (/home/greg/SE/node_modules/express/lib/response.js:1008:7)
>     at module.exports (/home/greg/SE/routes/views/base.js:2:6)
>     at Layer.handle [as handle_request] (/home/greg/SE/node_modules/express/lib/router/layer.js:95:5)
>     at next (/home/greg/SE/node_modules/express/lib/router/route.js:137:13)
>     at Route.dispatch (/home/greg/SE/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request] (/home/greg/SE/node_modules/express/lib/router/layer.js:95:5)
>     at /home/greg/SE/node_modules/express/lib/router/index.js:281:22
>     at param (/home/greg/SE/node_modules/express/lib/router/index.js:354:14)
>     at param (/home/greg/SE/node_modules/express/lib/router/index.js:365:14)
>     at Function.process_params (/home/greg/SE/node_modules/express/lib/router/index.js:410:3)
> GET /favicon.ico 500 8.089 ms
>

**Comment by nikeshpatel99** [comment]
Pull request #58  will fix.
