### ISSUE TITLE
System doesn't cover for non automated bookings

### ISSUE THREAD

**Issue by rowanho** [GKStretton/SE#68]
The client needs an interface to add a manual booking to the database, if they only use google calendar there is no easy way to check for a clash. This is due to the same calendar being used for multiple facilities.

**Comment by rowanho** [comment]
This could be covered with a relatively similar form to the automated booking form as is, just with the payment layer removed server side

**Comment by rowanho** [comment]
As far as I've looked into it, adding a custom page behind the keystone admin login is difficult.
However, it might be easier to add the bookings and locks to the keystone db. I'm not sure if this would require changes to me and erdal's code (as we've used mongoDB native style queries and not mongoose)

**Comment by GKStretton** [comment]
Can the system not check the google calendar for clashes?

As far as I can tell, we can't add custom admin pages. 
https://keystonejs.canny.io/feature-requests/p/admin-interface-extensibility
There's the option of treating bookings like any other model and adding entries in keystone like that, but it's a bit messy, and if the calendar is also being used it'll be in two places.

I'm not familiar with how the database/calendar are being utilized for bookings. But if the calendar is being used, shouldn't it all be on there?

**Comment by rowanho** [comment]
Google calendar has no system to formally specify an attribute of an event on the calendar. In this case, we'd need an attribute for facility on each calendar event. An automated event added to the calendar could have something like a json string eg "{"facility":"astro-turf"}" as its description. But it would be inconvenient for the client to have to manually type this out every time they added an event to the calendar. 

We could have a separate calendar for each facility though and that could overcome the issue. Otherwise manual bookings would have to be in the db.

**Comment by nikeshpatel99** [comment]
I'm pretty sure this has been sorted within the last 100 commits, so I'm closing this issue.
