### ISSUE TITLE
Duplicate facility data

### ISSUE THREAD

**Issue by GKStretton** [GKStretton/SE#82]
Currently there are two sections for facility price data, and 2 for availability as well.
These should be combined (get rid of user friendly/markdown one and pass the simple one on the front end).

**Comment by jack-tweddell** [comment]
@GKStretton If we do this for pricing, when PVCC want to enter a bespoke pricing model for a non-automated facility. (e.g Theatre) how would we display this pricing info?

**Comment by GKStretton** [comment]
Could keep the markdown box but have it as override. So if it's empty, front end will generate from the simple ones, else display the md.
