### ISSUE TITLE
Dealing with automated and bespoke bookings

### ISSUE THREAD

**Issue by rowanho** [GKStretton/SE#85]
Implementation for simple bookings (ie, the user books the whole facility with no bespoke options for a set time) works. However, the bespoke style bookings (ie with options, half/fractions of a facility) would be difficult to add to the database functionality given our limited time.

We could get around this by making the facilities with options fully non-automated.
The issue arises with how PVCC would interact with these non automated and automated bookings at the same time, as the automated bookings currently go onto a read only calendar which we don't want to mess around with.  Furthermore, PVCC has to add all their bookings for automated facilities through our form, so they go into the DB and can be checked for clashes

**Comment by jack-tweddell** [comment]
So if a facility has options that affect concurency it is non-automated. Should the options be editable by PVCC in keystone and appear on the manual booking request form (they don't right now)? If a user then makes a non-automated booking request will the options be sent to PVCC via the form?
