### ISSUE TITLE
Automated booking prices

### ISSUE THREAD

**Issue by nikeshpatel99** [GKStretton/SE#90]
Currently any transaction for a booking has the price of £0.01. The system needs to correctly calculate and charge the correct amount for a booking.

**Comment by jack-tweddell** [comment]
The pricing data is currently in a *goodish* format in keystone. 👍 

We've made *some* assumtions about their pricing structure for an automated booking, that they charge a set price for a set number of hours (1hr, 3hrs, 7hrs) . In the current model, they could add a new price for a different number of hours (e.g 2hrs) or omit a data point (e.g not including a 1hr price), so who ever does this calculation might need to take into account this extensibility, or else it needs to be included in **documentation** that they should not do this.

**In theory, when calculating the price, we can iteratively take the largest block of hours that doesn't go over the length of the booking. If no such block exists, we can take the smallest block that does go over the length of the booking.**

This may not always come up with the cheapest price, but I'm fairly sure that the issue there is with the actual prices on PVCC's side.

If no pricing data is entered by PVCC maybe it should default to a payment of £0 or £0.01?

If they wanted to completely change this pricing structure e.g (flat price for a facility, different prices per day etc.) then they would need a developer to change the system, or treat it as a manual facility, this is something that would go in the **documentation**.
